name: rental_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  card_swiper: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  http: ^1.2.0
  provider: ^6.1.1
  slide_to_act: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
